[package]
name = "rustos"
version = "0.1.0"
edition = "2021"

# El kernel no enlaza la biblioteca estándar.
[[bin]]
name = "rustos"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
# Activa cada crate en la etapa que lo usa:
# etapa 1  bootloader = "0.9"
# etapa 1  uart_16550 = "0.3"
# etapa 2  volatile = "0.4"
# etapa 2  spin = "0.9"
# etapa 3  x86_64 = "0.15"
# etapa 4  pic8259 = "0.10"
# etapa 2+ lazy_static = { version = "1.5", features = ["spin_no_std"] }
